services:
    postgresql:
        image: postgres:15.1
        container_name: postgres-container
        restart: always
        env_file: .env
        environment:
            POSTGRES_PASSWORD: ${SERVICE_DB_PASS}
            TZ: Asia/Jakarta
        ports:
            - 5432:5432
        volumes:
            - postgresql-volume:/var/lib/postgresql/data
        # uncomment if needed
        # mem_limit: 256m
        # cpus: 0.5

volumes:
    postgresql-volume:
