services:
    mongodb:
        image: mongo:7.0
        container_name: mongodb-container
        restart: always
        env_file: .env
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${SERVICE_DB_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${SERVICE_DB_PASS}
            TZ: Asia/Jakarta
        ports:
            - 27017:27017
        volumes:
            - mongodb-volume:/data/db
            - mongodb-volume:/data/configdb
        # uncomment if needed
        # mem_limit: 256m
        # cpus: 0.5

volumes:
    mongodb-volume:
