services:
    mariadb:
        image: mariadb:10.5
        container_name: mariadb-container
        restart: always
        env_file: .env
        environment:
            MARIADB_ROOT_PASSWORD: ${SERVICE_DB_PASS}
            TZ: Asia/Jakarta
        ports:
            - 3306:3306
        volumes:
            - mariadb-volume:/var/lib/mysql
        # uncomment if needed
        # mem_limit: 256m
        # cpus: 0.5

volumes:
    mariadb-volume:
