services:
    redis:
        image: redis:7.0
        container_name: redis-container
        restart: always
        env_file: .env
        environment:
            TZ: Asia/Jakarta
        ports:
            - 6379:6379
        volumes:
            - redis-volume:/data
        # uncomment if needed
        # mem_limit: 256m
        # cpus: 0.5

volumes:
    redis-volume:
