services:
    redis:
        image: redis:7.0
        container_name: redis-container
        restart: always
        env_file: .env
        environment:
            TZ: Asia/Jakarta
        ports:
            - 6379:6379
        volumes:
            - shared-redis-volume:/data
        networks:
            - shared-networks
        # uncomment if needed
        # mem_limit: 256m
        # cpus: 0.5

volumes:
    shared-redis-volume:

networks:
    shared-networks:
        external: true
