# version: '3.8'

services:
    postgres:
        image: postgres:15.6-alpine
        container_name: postgres-container
        restart: unless-stopped
        env_file: .env
        environment:
            POSTGRES_PASSWORD: ${SERVICE_DB_PASS}
            POSTGRES_DB: test_db
        volumes:
            - postgres_volume:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        # mem_limit: 512m
        # cpus: 1.0
        networks:
            - network

    redis:
        image: redis:7-alpine
        container_name: redis-container
        restart: unless-stopped
        env_file: .env
        command: redis-server --save 60 1 --loglevel warning --maxmemory 1gb --maxmemory-policy allkeys-lru
        volumes:
            - redis_volume:/data
        ports:
            - '6379:6379'
        # mem_limit: 512m
        # cpus: 1.0
        networks:
            - network

    mongodb:
        image: mongo:4.4
        container_name: mongodb-container
        restart: unless-stopped
        env_file: .env
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${SERVICE_DB_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${SERVICE_DB_PASS}
        volumes:
            - mongodb_volume:/data/db
            - mongodb_volume:/data/configdb
        ports:
            - '27017:27017'
        # mem_limit: 512m
        # cpus: 1.0
        networks:
            - network

volumes:
    postgres_volume:
        driver: local
    redis_volume:
        driver: local
    mongodb_volume:
        driver: local

networks:
    network:
        name: docker_network
        driver: bridge
