version: '3.8'

services:
    postgres:
        image: postgres:15.6-alpine
        container_name: postgres_db
        restart: unless-stopped
        env_file: .env
        environment:
            POSTGRES_PASSWORD: ${SERVICE_DB_PASS}
            POSTGRES_DB: test_db
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres -d test_db']
            interval: 5s
            timeout: 5s
            retries: 5
        mem_limit: 512m
        cpus: 1.0
        networks:
            - app_network

    redis:
        image: redis:7-alpine
        container_name: redis_cache
        restart: unless-stopped
        env_file: .env
        command: redis-server --save 60 1 --loglevel warning --maxmemory 1gb --maxmemory-policy allkeys-lru
        volumes:
            - redis_data:/data
        ports:
            - '6379:6379'
        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']
            interval: 5s
            timeout: 3s
            retries: 5
        mem_limit: 512m
        cpus: 1.0
        networks:
            - app_network

    mongodb:
        image: mongo:7.0.5-jammy
        container_name: mongo_db
        restart: unless-stopped
        env_file: .env
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${SERVICE_DB_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${SERVICE_DB_PASS}
        volumes:
            - mongo_data:/data/db
        ports:
            - '27017:27017'
        healthcheck:
            test: >
                CMD-SHELL echo 'db.runCommand("ping").ok' | mongosh -u ${SERVICE_DB_USER} -p ${SERVICE_DB_PASS} --quiet | grep 1
            interval: 5s
            timeout: 5s
            retries: 5
        mem_limit: 512m
        cpus: 1.0
        networks:
            - app_network

volumes:
    postgres_data:
        driver: local
    redis_data:
        driver: local
    mongo_data:
        driver: local

networks:
    app_network:
        driver: bridge
